export { default as ParlamentService } from './parlament.services';
export { default as CommitteeServices } from './committee.service';
export { default as FactionService } from './faction.service';
export { default as UnitService } from './unit.service';
export { default as CitizenReceptionService } from './text1.service';
export { default as StandingCommitteeService } from './text2.service ';
export { default as AcceptabilityService } from './acceptability.service';
export { default as SecondAcceptabilityService } from './second.acctability.service';
export { default as TimeStampServic } from './time.stamp.service';
export { default as SuperAdminService } from './super.admin.service';
